name: relay-gpio container

"on":
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "relay-gpio/**"
      - ".github/workflows/relay-gpio-container.yml"
  pull_request:
    paths:
      - "relay-gpio/**"
      - ".github/workflows/relay-gpio-container.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  docker:
    concurrency:
      group: relay-gpio-container-build
      cancel-in-progress: true
    uses: FyraLabs/actions/.github/workflows/docker.yml@main
    with:
      publish: ${{ github.event_name != 'pull_request' }}
      context: relay-gpio
      dockerfile: relay-gpio/Containerfile
      image_name: ${{ github.repository }}/relay-gpio
    secrets: inherit
